var ContextBuilder = require('./index.js');

var twilioData = {
	ToCountry: 'US',
	ToState: 'CT',
	SmsMessageSid: 'SM75ec801fb31d63be85550c5063280a89',
	NumMedia: '0',
	ToCity: 'SIMSBURY',
	FromZip: '19442',
	SmsSid: 'SM75ec801fb31d63be85550c5063280a89',
	FromState: 'PA',
	SmsStatus: 'received',
	FromCity: 'NORRISTOWN',
	Body: 'Hey',
	FromCountry: 'US',
	To: '+18607354841',
	ToZip: '06089',
	NumSegments: '1',
	MessageSid: 'SM75ec801fb31d63be85550c5063280a89',
	AccountSid: 'ACa313ac038893797140447ab4b4eb9932',
	From: '+16107336455',
	ApiVersion: '2010-04-01'
}


var githubData = {
  zen: 'Keep it logically awesome.',
  hook_id: 241352679,
  hook: {
    type: 'Repository',
    id: 241352679,
    name: 'web',
    active: true,
    events: [ 'push' ],
    config: {
      content_type: 'json',
      insecure_ssl: '0',
      url: 'https://rf-update-bot.glitch.me/github'
    },
    updated_at: '2020-08-14T07:22:02Z',
    created_at: '2020-08-14T07:22:02Z',
    url: 'https://api.github.com/repos/metatech-industries/metatech-website/hooks/241352679',
    test_url: 'https://api.github.com/repos/metatech-industries/metatech-website/hooks/241352679/test',
    ping_url: 'https://api.github.com/repos/metatech-industries/metatech-website/hooks/241352679/pings',
    last_response: { code: null, status: 'unused', message: null }
  },
  repository: {
    id: 287464900,
    node_id: 'MDEwOlJlcG9zaXRvcnkyODc0NjQ5MDA=',
    name: 'metatech-website',
    full_name: 'metatech-industries/metatech-website',
    private: true,
    owner: {
      login: 'metatech-industries',
      id: 68498584,
      node_id: 'MDQ6VXNlcjY4NDk4NTg0',
      avatar_url: 'https://avatars3.githubusercontent.com/u/68498584?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/metatech-industries',
      html_url: 'https://github.com/metatech-industries',
      followers_url: 'https://api.github.com/users/metatech-industries/followers',
      following_url: 'https://api.github.com/users/metatech-industries/following{/other_user}',
      gists_url: 'https://api.github.com/users/metatech-industries/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/metatech-industries/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/metatech-industries/subscriptions',
      organizations_url: 'https://api.github.com/users/metatech-industries/orgs',
      repos_url: 'https://api.github.com/users/metatech-industries/repos',
      events_url: 'https://api.github.com/users/metatech-industries/events{/privacy}',
      received_events_url: 'https://api.github.com/users/metatech-industries/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/metatech-industries/metatech-website',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/metatech-industries/metatech-website',
    forks_url: 'https://api.github.com/repos/metatech-industries/metatech-website/forks',
    keys_url: 'https://api.github.com/repos/metatech-industries/metatech-website/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/metatech-industries/metatech-website/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/metatech-industries/metatech-website/teams',
    hooks_url: 'https://api.github.com/repos/metatech-industries/metatech-website/hooks',
    issue_events_url: 'https://api.github.com/repos/metatech-industries/metatech-website/issues/events{/number}',
    events_url: 'https://api.github.com/repos/metatech-industries/metatech-website/events',
    assignees_url: 'https://api.github.com/repos/metatech-industries/metatech-website/assignees{/user}',
    branches_url: 'https://api.github.com/repos/metatech-industries/metatech-website/branches{/branch}',
    tags_url: 'https://api.github.com/repos/metatech-industries/metatech-website/tags',
    blobs_url: 'https://api.github.com/repos/metatech-industries/metatech-website/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/metatech-industries/metatech-website/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/metatech-industries/metatech-website/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/metatech-industries/metatech-website/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/metatech-industries/metatech-website/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/metatech-industries/metatech-website/languages',
    stargazers_url: 'https://api.github.com/repos/metatech-industries/metatech-website/stargazers',
    contributors_url: 'https://api.github.com/repos/metatech-industries/metatech-website/contributors',
    subscribers_url: 'https://api.github.com/repos/metatech-industries/metatech-website/subscribers',
    subscription_url: 'https://api.github.com/repos/metatech-industries/metatech-website/subscription',
    commits_url: 'https://api.github.com/repos/metatech-industries/metatech-website/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/metatech-industries/metatech-website/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/metatech-industries/metatech-website/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/metatech-industries/metatech-website/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/metatech-industries/metatech-website/contents/{+path}',
    compare_url: 'https://api.github.com/repos/metatech-industries/metatech-website/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/metatech-industries/metatech-website/merges',
    archive_url: 'https://api.github.com/repos/metatech-industries/metatech-website/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/metatech-industries/metatech-website/downloads',
    issues_url: 'https://api.github.com/repos/metatech-industries/metatech-website/issues{/number}',
    pulls_url: 'https://api.github.com/repos/metatech-industries/metatech-website/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/metatech-industries/metatech-website/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/metatech-industries/metatech-website/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/metatech-industries/metatech-website/labels{/name}',
    releases_url: 'https://api.github.com/repos/metatech-industries/metatech-website/releases{/id}',
    deployments_url: 'https://api.github.com/repos/metatech-industries/metatech-website/deployments',
    created_at: '2020-08-14T06:52:04Z',
    updated_at: '2020-08-14T07:21:02Z',
    pushed_at: '2020-08-14T07:21:00Z',
    git_url: 'git://github.com/metatech-industries/metatech-website.git',
    ssh_url: 'git@github.com:metatech-industries/metatech-website.git',
    clone_url: 'https://github.com/metatech-industries/metatech-website.git',
    svn_url: 'https://github.com/metatech-industries/metatech-website',
    homepage: null,
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'CSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master'
  },
  sender: {
    login: 'metatech-industries',
    id: 68498584,
    node_id: 'MDQ6VXNlcjY4NDk4NTg0',
    avatar_url: 'https://avatars3.githubusercontent.com/u/68498584?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/metatech-industries',
    html_url: 'https://github.com/metatech-industries',
    followers_url: 'https://api.github.com/users/metatech-industries/followers',
    following_url: 'https://api.github.com/users/metatech-industries/following{/other_user}',
    gists_url: 'https://api.github.com/users/metatech-industries/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/metatech-industries/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/metatech-industries/subscriptions',
    organizations_url: 'https://api.github.com/users/metatech-industries/orgs',
    repos_url: 'https://api.github.com/users/metatech-industries/repos',
    events_url: 'https://api.github.com/users/metatech-industries/events{/privacy}',
    received_events_url: 'https://api.github.com/users/metatech-industries/received_events',
    type: 'User',
    site_admin: false
  }
}




var twitch = new ContextBuilder.TwitchContext()
var discord = new ContextBuilder.DiscordContext()
var twilio = new ContextBuilder.TwilioContext(twilioData)
var github = new ContextBuilder.GithubContext(githubData)

console.log(github)
// console.log(twitch)
// console.log(discord)
// console.log(twilio)